[backup]
backup_period = "0 */1 * * *"
sending_backup_period = "0 0 */1 * *"

[payments.qiwi]
is_active = true
payment_method = "number"

[payments.yoomoney]
is_active = true

[payments.minerlock]
is_active = false

[payments.coinpayments]
is_active = false

[payments.coinbase]
is_active = true
